sudo: false
language: python
python:
  - "2.7"
#  - "3.6"
#addons:
#  apt:
#    sources:
#      - deadsnakes
#    packages:
#      - python2.4
#      - python2.6
#      - python2.7
#      - python3.5
#      - python3.6
env:
  global: 
  #caas_username
    - secure: "hlgY8sIP9gl6R+wX6BhBvEf8WDOegN5YTs0pFQChKZ4lKo8IGuSkaAQeZ3h13D+fELEbWKtcHi99COCpW4sOORj0u8B8sP92mtMZXvFZdB+cF23QfyFDHRd9GeksJTdRGstuJuJhBJodAxVU0Vo/3KW1Q63ijSpUz/OI4w+DqUPYIUf73AV4T3+yauC9I45RhIOEwFWk/A8IPK8aeBtzuqL1Se0GWnPW3xIqJHjjMTuh1v/GiM2dZDuvZPg0IN4OW/pyX/vW4Tw4A910h3oWqxhfFX6sHAO06tJeywwEM4pSaVOecXajOAHkGUaJnsjHvI2XmOmd7Y6krZalVizUuPPbJu/ERoT6GhRh9bIrQLnlED0VBtVY6BM1GrMTb72UeAYEYsyYWtZQxlclZJbvtR3o+ULHHydwD8/M6e1YHBeioFJKprpWGwkrTf2Tl6Xci8fKO6ykY3IWJCmesREjcEh1nBwZJAmDT4yHFs7GKNGFdrCaw60/ztqdqBr5j2E+o0fPt9HlnYyRNZezNSuHnpQedt1gj8BUc2yBgq20D7Z77qQP00BzSb4xgwe2mVHzgxE32aYOIcvPmcPiVGSByAq1kwyZCpkOMpD+6kDzYlGPXPYOVDmrEE9nz+PIte/Das9A7T/7Oaai7WaJXOto4mMXrmw+FsAO7VOJRebfJgg="
  #caas_password
    - secure: "GrKqI60n8RfHXzlZ73j2Nks4xPQxGEle8xTE61f26Ybnma6MGm9/DXMra3OpaRKm2PxErJuhlfz52fmkmcIbbsE3SsY28unaujadTndW0q016GqFt7Wu/0FzEuhVM4q4uyMsBHSOP2kwjzAb9Vo6UiL5gM6PCYYBVmfUtw8v3Kjo7QNTkEaVCeHN5gpgFNHQO8GfTmMQTEbEvI2eTOOmeUi0EgVcNLd7HziDmsAz/5Vg7D/AICSaYC4zVpi3DBWKXynqFQwDUX2Pfm7sEOm8UQcNZdmLwRWsRrm/WVK2bYdWEcPjXXWvysgQX+BAgHxugNA4y2/bAEno3bQd4t6ZdgN0C9La7k903R5Nk3BaLAMKL2rHp0b/XWQ9h7/LjARjps+i+SBp/9IpNKuJQFAGrfZNfXL9Te/e1TmxQhaK9PHxV4sAAMlwnHLGiPd3omaGRpdPc166oRNbNGdHgpAwfkIJh3MY1SeFZ6p0U6JV1AiyJlaiPI0cOQjPctrtMKj5qx72Bcxc+yg0lPBxd6plO8Duq75P0U/+wt6XZEKTndNKoyy0iJk0E1GqQM2xAzPc9on8uuguJRGZ4Paymmi0LaMHcLh4VgX+jBKk4tJbSgh+K+ZyXjFd8Rxz0XKiTpHDegGTF9+yOlM9QkLW6DMp+wi+i2RGwO0hVuIpTUw2gHU="
  matrix:
#    - ansible_branche=stable-1.9 test=False caas_networkdomain=ansible1.9.CaaS_travis-ci
#    - ansible_branche=stable-2.0 test=False caas_networkdomain=ansible2.0.CaaS_travis-ci
#    - ansible_branche=stable-2.1 test=True caas_networkdomain=ansible2.1.CaaS_travis-ci
    - ansible_branche=stable-2.6 test=True caas_networkdomain=ansible2.6.CaaS_travis-ci
#    - ansible_branche=devel      test=True caas_networkdomain=ansibledevel.CaaS_travis-ci
before_install:
 - pip install tox paramiko PyYAML jinja2 httplib2 passlib nose mock
install:
 - git clone --branch=$ansible_branche git://github.com/ansible/ansible.git --recursive /home/travis/build/ansible
 - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
 - source /home/travis/build/ansible/hacking/env-setup
# - ln -s /home/travis/build/job-so/ansible.CaaS/library /home/travis/build/ansible/lib/ansible/modules/extras/cloud/dimension_data
 - ln -s /home/travis/build/job-so/ansible.CaaS/library /home/travis/build/ansible/lib/ansible/modules/cloud/dimension_data
script:
  - sed -e "s/firstname.lastname/$caas_username/g" -e "s/MySecret_KeepItSecret/$caas_password/g" caas_credentials.yml > test/caas_credentials.yml
  - touch hosts
  #- python2.4 -m compileall -fq library
  #- python2.6 -m compileall -fq library
  - python2.7 -m compileall -fq library
  #- python3.5 -m compileall -fq library
  - ansible-playbook --version
  - ansible-playbook -i ./hosts test/01-setup.yml
  - ansible-playbook -i ./hosts test/99-teardown.yml
  
# From ansible/modules-extras
  - if test x"$test" == x'True' ; then ansible-validate-modules library ; fi
  
# From ansible/ansible
# urllib2's defaults are not secure enough for us
  - cd /home/travis/build/ansible
  - if test x"$test" = x'True' ; then ./test/code-smell/replace-urlopen.sh . ; fi
  - if test x"$test" = x'True' ; then ./test/code-smell/use-compat-six.sh lib ; fi
  - if test x"$test" = x'True' ; then ./test/code-smell/boilerplate.sh ; fi
  - if test x"$test" = x'True' ; then ./test/code-smell/required-and-default-attributes.sh ; fi
#  - if test x"$TOXENV" != x'py24' ; then tox ; fi
#  - if test x"$TOXENV" = x'py24' ; then python2.4 -V && python2.4 -m compileall -fq -x 'module_utils/(a10|rax|openstack|ec2|gce).py' lib/ansible/module_utils ; fi
  #- make -C docsite all
#  - if test x"$INTEGRATION" = x'yes' ; then source ./hacking/env-setup && cd test/integration/ && make parsing && make test_var_precedence && make unicode ; fi
after_success:
  - coveralls