sudo: false
language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
#    sources:
#      - deadsnakes
#    packages:
#      - python2.4
#      - python2.6
#      - python2.7
#      - python3.5
#      - python3.6
env:
  global: 
  #caas_username
    - secure: "g6sEOPBA5LTTDnIgdv1SPAw3KlJzYCt8HPIrnnEwlPvThDuNBx1F4PFY88CeOBIoV0Vo8Kn0gR93CP5WN1RGDgsPSSG2bOjE18PusYt3eRYGyLulHC44ghWdkgfHBPe5GcctK8uuO3/i+5xWGQ1+HDca+uX+Us725uyTcT/cLs1KnlTnG/gQqJ0uoccFE0VgOGQLd4XLPhRNIsom2hgX8iaO6XceHufCRc6ea76hlpKIkxrQ3aHbj0kHXSboxTAepon2vgAOOoHnGcC6x8ATbmoj8N0prkiAwXEa+SkW1jDoWHpHw45guzcsf95EGMmiyB/O+TVNeDdAsnSzfnVXX1Sxv6Xkgx5hMaGVUUtrTPszNI87DbzU0Se/+kVvIfV2ReQ1YJDKT5LH+SIcR2f/O80J6+mpHx0nSYg2a1c7IQr1Nyn0hLE+56lRP/3UVDE63xaz/xmoQlAGfxJYRAPHfiqBpQPlscGauaUAh0Nt1EZabsQx3+B7HlI/W+fmP2E/j6h/DkHU6dz6uU+6I/+rrk03Nueo97oUVb1mrN01FVO0zeQkzErvzJbE2f0WMV1SWBci8+9bZX9ZzIEAH0iApNnJ/nVb6pOKSDRj7EizhGmxDS0Ae/RGTmdcdPXCOK8IwxCexJCu5YWbiDFtT1GZ7dlm0hFpYaI9cAHPFJbHHAQ="
  #caas_password
    - secure: "l05r1FmdG8S7/KfDIFM/MfKzeu+9w39y94v6UzJ/49apNJKDSUvp0QLB08u34pyE1Jc/klCUsuBTFH0iQJQSYlkXPxro3PgmEsKBLtklIuvt/1hju7lLrixl/8C6L+X4Y722Fs7YAzpWRJtDgA2XN3b68tCXQpnoIA9Lih1ARQXG0Nojs24+cOWy+q+z5Uoc0UteGH507LjpNG5Fm7I1g9xUp+ZcgMJqxYndVnKiZmTWMeKS3cVa4lE8m77YulKVrDt+WfPc8BcNb+ggZaRleZZfbxynHjNtvEumVR+fbFTsGYcDfslILJhPT7JEXiTWdI6uuCzwlsJbxG/nbEtuXs7wN1qRVsVIHCeTx5QCfX+nATu5rqBrN5vo3eoi5JVL24Ezh73Hqy0ZTs9TxIU2hr6poquyhmzMCchmtEbtrH4LWQzqMmgDSF44Mclmdu8chpytrEJUxcQx2IziiadM4XWMnkq0Zggfx+fTQKTpJSkTOBn1vgWZ96mY1s00tQoOauZALP+p14rK9DOs+/Q82zwZ8wFjkXPDlszU9PpJbkqrqn0UEqG1yfEDMcjVcx8+vW2iMRNjfRm4QzOSHRccd06NmwCKgrjlwEX3vxRD2dXsRyz6JmhPkE0tfxyAY4ZjTCTeONgXXYTLDUQYc8QK8qzSGRXhJeWOFzxcDG3hNYU="
  matrix:
#    - ansible_branche=stable-1.9 test=False caas_networkdomain=ansible1.9.CaaS_travis-ci
#    - ansible_branche=stable-2.0 test=False caas_networkdomain=ansible2.0.CaaS_travis-ci
#    - ansible_branche=stable-2.1 test=True caas_networkdomain=ansible2.1.CaaS_travis-ci
    - ansible_branche=stable-2.6 test=True caas_networkdomain=ansible2.6.CaaS_travis-ci
#    - ansible_branche=devel      test=True caas_networkdomain=ansibledevel.CaaS_travis-ci
before_install:
 - pip install tox paramiko PyYAML jinja2 httplib2 passlib nose mock
install:
 - git clone --branch=$ansible_branche git://github.com/ansible/ansible.git --recursive /home/travis/build/ansible
 - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
 - source /home/travis/build/ansible/hacking/env-setup
 - ln -s /home/travis/build/job-so/ansible.CaaS/library /home/travis/build/ansible/lib/ansible/modules/extras/cloud/dimension_data
script:
  - sed -e "s/firstname.lastname/$caas_username/g" -e "s/MySecret_KeepItSecret/$caas_password/g" caas_credentials.yml > test/caas_credentials.yml
  - touch hosts
  #- python2.4 -m compileall -fq library
  #- python2.6 -m compileall -fq library
  - python2.7 -m compileall -fq library
  #- python3.5 -m compileall -fq library
  - ansible-playbook --version
  - ansible-playbook -i ./hosts test/01-setup.yml
  - ansible-playbook -i ./hosts test/99-teardown.yml
  
# From ansible/modules-extras
  - if test x"$test" == x'True' ; then ansible-validate-modules library ; fi
  
# From ansible/ansible
# urllib2's defaults are not secure enough for us
  - cd /home/travis/build/ansible
  - if test x"$test" = x'True' ; then ./test/code-smell/replace-urlopen.sh . ; fi
  - if test x"$test" = x'True' ; then ./test/code-smell/use-compat-six.sh lib ; fi
  - if test x"$test" = x'True' ; then ./test/code-smell/boilerplate.sh ; fi
  - if test x"$test" = x'True' ; then ./test/code-smell/required-and-default-attributes.sh ; fi
#  - if test x"$TOXENV" != x'py24' ; then tox ; fi
#  - if test x"$TOXENV" = x'py24' ; then python2.4 -V && python2.4 -m compileall -fq -x 'module_utils/(a10|rax|openstack|ec2|gce).py' lib/ansible/module_utils ; fi
  #- make -C docsite all
#  - if test x"$INTEGRATION" = x'yes' ; then source ./hacking/env-setup && cd test/integration/ && make parsing && make test_var_precedence && make unicode ; fi
after_success:
  - coveralls